#!/bin/bash

#SBATCH --job-name=qsmxt
#SBATCH --ntasks-per-node=4
#SBATCH --mem=16G
#SBATCH --time=01:00:00

export container=qsmxt_7.2.0_20240830

echo "[INFO] Pulling QSMxT singularity container... (US)"
#curl -X --no-progress-meter GET https://neurocontainers.neurodesk.org/${container}.simg --output ${container}.simg
export SINGULARITY_TMPDIR=`pwd`
singularity --quiet pull ${container}.simg docker://vnmd/qsmxt_7.2.0:20240830

echo "[INFO] Installing pip dependencies..."
singularity exec ${container}.simg pip install -U pip
singularity exec ${container}.simg pip install -U scikit-image

echo "[INFO] Starting main.py..."
singularity exec ${container}.simg python3 main.py

