#!/bin/bash

#SBATCH --job-name=qsmxt
#SBATCH --ntasks-per-node=4
#SBATCH --mem=16G
#SBATCH --time=01:00:00

export container=qsmxt_7.2.0_20240830

echo "[INFO] Pulling QSMxT singularity container... (US)"
curl --no-progress-meter -X GET https://neurocontainers.neurodesk.org/${container}.simg -O
echo "[INFO] Finished pulling QSMxT singularity container!"

echo "[INFO] Current directory is $(pwd)"
echo "[INFO] Listing files in current directory $(ls)"
ls -l

echo "[INFO] Installing pip dependencies..."
singularity exec ${container}.simg pip install -U pip
singularity exec ${container}.simg pip install -U scikit-image

echo "[INFO] Starting main.py..."
singularity exec ${container}.simg python3 main.py

